<a href="https://colab.research.google.com/github/janani-06032005/machinelearning-part1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numerical python

In [ ]:
import numpy as np

Numpy array functions

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


finding shape

In [ ]:
a.shape

(4,)

creating 2d array

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

finding datatype


In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial place holders in numpy arrays

In [ ]:
#creating numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#creating numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create the numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.27885205 0.79640057 0.79249745 0.23774579]
 [0.77677002 0.5164678  0.01900839 0.07543296]
 [0.30210911 0.33418099 0.84870072 0.19323683]]


In [ ]:
#creating the random integer values
b=np.random.randint(10,100,(3,5))
print(b)

[[53 72 95 62 62]
 [70 47 52 17 44]
 [35 51 99 47 42]]


In [ ]:
#array of evenly spaced values
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
#array of evenly spaced values
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#converting list to numpy arrays
list=[10,20,30,40,50]
np_array=np.array(list)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

analysing numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[62 19 52 15 57]
 [12 76 18 75 44]
 [86 43 42 86 29]
 [47 39 20 73 50]
 [22 33 26 43 76]]


In [ ]:
print(c.shape)

(5, 5)


In [ ]:
#no:of dimensions
print(c.ndim)


2


In [ ]:
#number of elements in array
print(c.size)

25


In [ ]:
#checking the datatype of the values in the array
print(c.dtype)

int64


mathematical operations on np array

In [ ]:
list1 = [1,2,3,4,5,6]
list2 = [6,7,8,9,3,4]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 3, 4]


In [ ]:
#addition
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 7 4]
 [2 7 8]
 [3 8 8]]
[[18 19 13]
 [12 15 17]
 [12 13 16]]


array manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 8 1]
 [0 1 6]]
(2, 3)


In [ ]:
#transpose of matrix
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[0 0]
 [8 1]
 [1 6]]
(3, 2)


In [ ]:
#another method for transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 0]
 [8 1]
 [1 6]]
(3, 2)


In [ ]:
#reshape a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 2 8]
 [8 6 8]]
(2, 3)
